# Generated by Django 5.2.3 on 2025-07-01 11:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('testcase', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='TestTaskRun',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
				('title', models.TextField()),
				(
					'status',
					models.CharField(
						choices=[
							('Scheduled', 'Scheduled'),
							('Queued', 'Queued'),
							('Running', 'Running'),
							('Canceled', 'Canceled'),
							('Pass', 'Pass'),
							('Failed', 'Failed'),
						],
						max_length=20,
					),
				),
				('test_data', models.JSONField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				(
					'test_case_run',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='testcase.testcaserun',
					),
				),
			],
		),
	]
