# Generated by Django 5.2.3 on 2025-07-05 08:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('testask', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='testtaskrun',
			name='test_task_uuid',
			field=models.UUIDField(blank=True, null=True),
		),
		migrations.AlterField(
			model_name='testtaskrun',
			name='test_data',
			field=models.JSONField(blank=True, null=True),
		),
		migrations.AlterField(
			model_name='testtaskrun',
			name='uuid',
			field=models.UUIDField(blank=True, null=True, unique=True),
		),
		migrations.AlterField(model_name='testtaskrun', name='test_task_uuid', field=models.UUIDField()),
		migrations.AlterField(
			model_name='testtaskrun',
			name='uuid',
			field=models.UUIDField(unique=True, default=uuid.uuid4),
		),
	]
