# Generated by Django 5.2.3 on 2025-07-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('testask', '0002_testtaskrun_test_task_uuid_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='testtaskrun',
			name='failure_screenshot',
			field=models.URLField(blank=True, null=True),
		),
	]
