# Generated by Django 5.2.3 on 2025-07-01 11:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name='LLMCache',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('caching_hash', models.TextField(blank=True, null=True, unique=True)),
				('llm_output', models.JSONField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
			],
		),
		migrations.CreateModel(
			name='TestCaseRun',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('job_uuid', models.UUIDField()),
				('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
				('environment', models.JSONField()),
				('base_url', models.URLField(max_length=255)),
				(
					'status',
					models.CharField(
						choices=[
							('Scheduled', 'Scheduled'),
							('Queued', 'Queued'),
							('Running', 'Running'),
							('Canceled', 'Canceled'),
							('Pass', 'Pass'),
							('Failed', 'Failed'),
						],
						max_length=20,
					),
				),
				('video', models.URLField(blank=True, null=True)),
				('failure_screenshot', models.URLField(blank=True, null=True)),
				('llm', models.CharField(blank=True, max_length=127, null=True)),
				(
					'browser',
					models.CharField(
						choices=[
							('chrome', 'Chrome'),
							('firefox', 'Firefox'),
							('safari', 'Safari'),
							('edge', 'Edge'),
						],
						max_length=20,
					),
				),
				('browser_session', models.TextField()),
				('is_headless', models.BooleanField(default=False)),
				('system_prompt_hash', models.TextField(blank=True, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('created_by', models.CharField(max_length=127)),
			],
		),
	]
