# Generated by Django 5.2.3 on 2025-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('testcase', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='testcaserun',
			name='test_case_uuid',
			field=models.UUIDField(blank=True, null=True),
		),
		migrations.AlterField(
			model_name='testcaserun',
			name='test_case_uuid',
			field=models.UUIDField(),
		),
	]
