# Generated by Django 5.2.3 on 2025-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('testcase', '0002_testcaserun_test_case_uuid'),
	]

	operations = [
		migrations.AlterField(
			model_name='testcaserun',
			name='browser_session',
			field=models.TextField(blank=True, null=True),
		),
		migrations.AlterField(
			model_name='testcaserun',
			name='created_by',
			field=models.JSONField(blank=True, null=True),
		),
	]
