# Generated by Django 5.2.3 on 2025-07-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('job', '0002_remove_job_uuid_job_job_uuid'),
		('testcase', '0004_testcaserun_name_testcaserun_priority'),
	]

	operations = [
		migrations.AddField(
			model_name='testcaserun',
			name='job',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='job.job',
			),
		),
		migrations.AlterField(
			model_name='testcaserun',
			name='job',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				to='job.job',
			),
		),
	]
