# Generated by Django 5.2.3 on 2025-07-12 07:20

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('testcase', '0005_testcaserun_job'),
	]

	operations = [
		migrations.RemoveField(
			model_name='testcaserun',
			name='failure_screenshot',
		),
	]
