# Generated by Django 5.2.4 on 2025-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('testcase', '0005_testcaserun_job'),
	]

	operations = [
		migrations.AlterField(
			model_name='testcaserun',
			name='video',
			field=models.CharField(blank=True, max_length=511, null=True),
		),
	]
