# Generated by Django 5.2.4 on 2025-07-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('testcase', '0006_alter_testcaserun_video'),
	]

	operations = [
		migrations.AlterField(
			model_name='testcaserun',
			name='test_case_uuid',
			field=models.UUIDField(db_index=True),
		),
	]
