# Generated by Django 5.2.3 on 2025-07-01 11:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('testask', '0001_initial'),
		('testcase', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='TestStepRun',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
				(
					'status',
					models.CharField(
						choices=[
							('Scheduled', 'Scheduled'),
							('Queued', 'Queued'),
							('Running', 'Running'),
							('Canceled', 'Canceled'),
							('Pass', 'Pass'),
							('Failed', 'Failed'),
						],
						max_length=20,
					),
				),
				('action', models.JSONField()),
				('result', models.CharField(max_length=255)),
				('llm_input', models.TextField()),
				('llm_output', models.JSONField()),
				('llm_input_tokens', models.IntegerField()),
				('llm_output_tokens', models.IntegerField()),
				('llm_thinking', models.TextField(blank=True, null=True)),
				('llm_time_taken', models.FloatField()),
				('network_requests', models.JSONField()),
				('console', models.TextField()),
				('current_url', models.URLField()),
				('caching_hash', models.TextField(blank=True, null=True)),
				('screenshot', models.URLField(blank=True, null=True)),
				('agent_history', models.TextField()),
				('DOM', models.TextField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				(
					'test_case_run',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='testcase.testcaserun',
					),
				),
				(
					'test_task_run',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='testask.testtaskrun',
					),
				),
			],
		),
	]
