# Generated by Django 5.2.3 on 2025-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name='PlayGround',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('playground_uuid', models.UUIDField(unique=True)),
				('data', models.JSONField()),
				('run_by', models.JSONField()),
				('business', models.IntegerField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
			],
		),
	]
