# Generated by Django 5.2.3 on 2025-07-04 08:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name='Job',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
				('test_case_uuid', models.UUIDField(blank=True, null=True)),
				('test_suite_uuid', models.UUIDField(blank=True, null=True)),
				('environment', models.JSONField()),
				(
					'job_type',
					models.CharField(
						choices=[('TestCase', 'TestCase'), ('TestSuite', 'TestSuite')],
						max_length=20,
					),
				),
				(
					'status',
					models.CharField(
						choices=[
							('Scheduled', 'Scheduled'),
							('Queued', 'Queued'),
							('Running', 'Running'),
							('Canceled', 'Canceled'),
							('Pass', 'Pass'),
							('Failed', 'Failed'),
						],
						max_length=20,
					),
				),
				('business', models.IntegerField()),
				('project', models.IntegerField()),
				('created_by', models.JSONField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('experimental', models.BooleanField(default=False)),
				('payload', models.JSONField()),
			],
		),
	]
