# Generated by Django 5.2.3 on 2025-07-04 09:41

import uuid

from django.db import migrations, models


def backfill_job_uuid(apps, schema_editor):
	Job = apps.get_model('job', 'Job')
	for job in Job.objects.filter(job_uuid__isnull=True):
		job.job_uuid = uuid.uuid4()
		job.save(update_fields=['job_uuid'])


class Migration(migrations.Migration):
	dependencies = [
		('job', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='job',
			name='uuid',
		),
		migrations.AddField(
			model_name='job',
			name='job_uuid',
			field=models.UUIDField(blank=True, default=None, null=True, unique=True),
		),
		migrations.RunPython(backfill_job_uuid, reverse_code=migrations.RunPython.noop),
		migrations.AlterField(
			model_name='job',
			name='job_uuid',
			field=models.UUIDField(unique=True, default=uuid.uuid4),
		),
	]
