name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pre-commit run check-toml          --all-files
      - run: pre-commit run check-yaml          --all-files
      - run: pre-commit run end-of-file-fixer   --all-files
      - run: pre-commit run trailing-whitespace --all-files
