name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: ${{ matrix.task }}  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [syntax, style, typecheck]

    steps:
      - uses: actions/checkout@v4
      - name: Setup uv and cache packages
        uses: astral-sh/setup-uv@v5
      - name: Run lint task
        run: |
          case "${{ matrix.task }}" in
            syntax) uv run ruff check --no-fix --select PLE ;;
            style)  uv run ruff format && uv run pre-commit run --all-files ;;
            typecheck) uv run pyright ;;
          esac
