name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
    
jobs:
  test:
    name: ${{ matrix.test }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [tests/browser, tests/models, tests/functionality, tests/all]
        

    steps:
      - uses: actions/checkout@v4
      - name: Setup uv and cache packages
        uses: astral-sh/setup-uv@v5
      - name: Run lint task
        run: |
          case "${{ matrix.test }}" in
            tests/browser) uv run --with=dotenv pytest tests/test_browser.py || true ;;
            tests/models)  uv run --with=dotenv pytest tests/test_models.py || true  ;;
            tests/functionality) uv run --with=dotenv pytest test_core_functionality.py || true ;;
            tests/all) uv run --with=dotenv pytest || true ;;
          esac


# TODO: Fix the ignored pytests.
# openai.OpenAIError: The api_key client option must be set either by passing
# api_key to the client or by setting the OPENAI_API_KEY environment variable
  #  uv run --with=dotenv pytest
  #     --ignore=tests/test_dropdown_error.py
  #     --ignore=tests/test_gif_path.py
  #     --ignore=tests/test_models.py
  #     --ignore=tests/test_react_dropdown.py
  #     --ignore=tests/test_save_conversation.py
  #     --ignore=tests/test_vision.py
  #     --ignore=tests/test_wait_for_element.py || true ;;
                      

      
